on:
  push:
    paths:
      - initial-setup.json
    branches:
      - main

name: Initial project setup

jobs:
  setup:
    # Don't run just after creating repo from template
    if: ( github.run_number != 1 ) && ${{ !contains (github.repository, '/thallium-microservice-template') }}
    name: Initial project setup
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup from initial-setup.py
      run: |
        python3 "${GITHUB_WORKSPACE}/.github/initial-setup.py"

    - uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: Initial project setup from template
